domain_path: /mnt/c/Users/Quan/Desktop/NTT-FPGA/Validation/ntt_platform/zynqmp_pmufw/zynqmp_pmufw_bsp
app_src_dir: C:\AMDDesignTools\2025.2.1\Vitis\data\embeddedsw\lib\sw_apps\zynqmp_pmufw
template: zynqmp_pmufw
lang: c
